#! /bin/bash 

cat log.txt|grep "10/Oct/2006" log.txt | cut -f12 -d" "| cut -f1 -d"/"| sort -k1| uniq -c| sort -r -k1 -n| cat -n| awk ' { print $1 ". " $3 " - " $2 " - " int($2*100/342) "%" } ' | head
#$(echo " int($2*100) "/$total| bc)%"
